### ISSUE TITLE
Lister les utilisateurs

### ISSUE THREAD

**Issue by jln-brtn** [crackito-io/crackito#2]
### Description
L'objectif de cette issue est de permettre de lister les utilisateurs dans le panel administrateur.

### Cas d'usage

| Acteur | Action | Résultat |
|--------|--------|--------|
| Utilisateur ayant les droits pour lister les utilisateurs | se rendre à l'url `/admin/accounts` | La liste des utilisateurs de la même organisation est affichée (elle comprend l'avatar, le nom, le prénom) |
| Utilisateur n'ayant pas les droits de lister les utilisateurs | se rendre à l'url `/admin/accounts` | L'utilisateur est retourné sur sa page précédente avec le message d'erreur "You do not have the rights to list users. Please contact your organisation's administrator."|

**Comment by jln-brtn** [comment]
@enzolouis Pour les erreurs, je te conseille de regarder comment [renvoyer les utilisateurs sur la page précédente](https://docs.adonisjs.com/guides/response#redirect-back-to-the-previous-page). Et aussi comment utiliser la fonctionnalité des [Flash Message](https://docs.adonisjs.com/guides/session#flash-messages) d'adonis.

**Comment by jln-brtn** [comment]
@enzolouis Pour la gestion des permissions, elles seront stockées coté utilisateur dans le JWT via des [Bit field](https://en.wikipedia.org/wiki/Bit_field).
En gros, chaque bit va représenter une permission. La combinaison de ces bits, activés ou non, donnera les permissions de l'utilisateur. Pour mémoire, le [Bitwise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Bitwise_AND) pourrait être bien utile.
Il faudra créer un fichier statique de configuration détaillant les différentes permissions et leurs bits.

**Comment by jln-brtn** [comment]
> @jln-brtn L'administrateur de l'organisation doit-il être affiché dans la liste des utilisateurs ?

Oui, toutes les personnes sans exception faisant partie de l'organisation doivent être affichée.

**Comment by enzolouis** [comment]
> > @jln-brtn L'administrateur de l'organisation doit-il être affiché dans la liste des utilisateurs ?
> 
> Oui, toutes les personnes sans exception faisant partie de l'organisation doivent être affichées.

D'accord, dans ce cas est-ce que, étant donné que mathématiquement la personne qui fera la requête est dans l'organisation il ne peut donc y avoir une liste vide.
La condition suivante :
![image](https://github.com/crackito-io/crackito/assets/65914622/d28fdb8c-110b-41ac-bb21-f4a337154420)
`// affichage de la liste...`
![image](https://github.com/crackito-io/crackito/assets/65914622/4a7332b0-8d50-41e4-9e5f-4a8dd6d1ac04)

menant à ceci (si aucun utilisateur n'appartient à l'organisation) :
![image](https://github.com/crackito-io/crackito/assets/65914622/0f4188a2-5483-4192-a4b9-e0f3ecdbe1cc)

La condition ci-dessus peut-elle être supprimé ou est-ce qu'on la garde dans le cas d'un bug un peu indeterminé

**Comment by jln-brtn** [comment]
> La condition ci-dessus peut-elle être supprimé ou est-ce qu'on la garde dans le cas d'un bug un peu indeterminé

Je serais partant de la garder pour le cas obscur.

**Comment by enzolouis** [comment]
Le breadcrumb devra-t-il être multi-langues ?

**Comment by jln-brtn** [comment]
> Le breadcrumb devra-t-il être multi-langues ?

Idéalement oui

**Comment by jln-brtn** [comment]
> Est-ce qu'il existera des cas où une page nécessite plus de 1 permission pour y accéder ?

Là, je n'ai pas d'exemple qui me vient en tête, mais je pense que oui

**Comment by jln-brtn** [comment]
# 🐞 Bug
**Description :**
Lorsque l'utilisateur n'est pas connecté et qu'il souhaite se rendre sur `/admin/accounts`, une erreur survient : `Invalid token specified: must be a string`
L'erreur se trouve `app/middleware/permissions_middleware.ts:8:27`

**Reproduction du comportement :**
Dans son navigateur, supprimer les cookies dédiés au domaine, puis naviguer sur l'URL `http://127.0.0.1:3333/admin/accounts`

** Comportement souhaité : **
L'utilisateur doit être redirigé sur la page de connexion

@enzolouis
