### ISSUE TITLE
Migration des permissions

### ISSUE THREAD

**Issue by jln-brtn** [crackito-io/crackito#4]
### Description
L'objectif de cette issue est de migrer les permissions, actuellement dans un fichier, vers la base de données.

### Cas d'usage
Aucune modification des cas d'usage. Le système doit respecter les précédentes spécifications.

### Notes
Le schéma de la BDD devra évoluer, notamment la partie permission qui devra stocker avoir comme clé principale un entier. Idéalement, les entiers devront être contigus (ne pas posséder de "trous") malgré des insertions et suppression. Ceci dans l'objectif de respecter le bit field.

**Comment by enzolouis** [comment]
Il vaut mieux peut-être ne pas utiliser de système d'entier contigus, ça implique de gérer en amont les données insérées pour respecter l'ordre et éviter les trous, on pourrait repartir sur le système d'origine, et faire simplement par ordre alphabétique sur le code de la permission

**Comment by enzolouis** [comment]
Les 4 actions liés aux utilisateurs (view, create, edit, delete) ne sont accessible qu'à l'administrateur ?

**Comment by jln-brtn** [comment]
Pas forcément, ce sera au super admin de l'organisation de définir à quels rôles ces actions sont liées. Il peut donc créer les rôles "enseignant" et "assistante pédagogique" qui possèderont tous les deux les 4 permissions.

**Comment by enzolouis** [comment]
D'accord, donc la seul table concerné par la migration est la table permission, j'avais créé les rôles de bases en leur mettant des permissions, je garde uniquement les migrations sur la permission ?

**Comment by jln-brtn** [comment]
Oui, on est pas encore aux rôles
