### ISSUE TITLE
Supprimer un utilisateur

### ISSUE THREAD

**Issue by enzolouis** [crackito-io/crackito#7]
### Description
L'objectif de cette issue est de permettre de supprimer un utilisateur dans le panel administrateur depuis la page de liste des utilisateurs.

### Cas d'usage

| Acteur | Action | Résultat |
|--------|--------|--------|
| Utilisateur ayant les droits pour supprimer un utilisateur | cliquer sur le bouton de suppression puis cliquer sur le bouton de confirmation de suppression dans la pop-up | Une requête HTTP en AJAX est envoyé sur l'url  `/admin/accounts/<user_id>` en méthode `DELETE` et l'utilisateur reçoit sur la page courante le *message de retour* (voir suite) |
| Utilisateur n'ayant pas les droits de supprimer un utilisateur | cliquer sur le bouton grisé de suppression | Rien ne se passe |
| Utilisateur ayant les droits pour supprimer un utilisateur | se rendre à l'url `/admin/accounts/<user_id>` en méthode `DELETE` | L'utilisateur reçoit une réponse **200** avec le message de succès *"The user is now deleted"* et l'utilisateur `user_id` est supprimé |
| Utilisateur n'ayant pas les droits de supprimer un utilisateur | se rendre à l'url `/admin/accounts/<user_id>` en méthode `DELETE` | L'utilisateur reçoit une réponse **403** avec le message d'erreur *"You do not have the rights to delete users. Please contact your organisation's administrator."* |
| Utilisateur ayant les droits pour supprimer un utilisateur | se rendre à l'url `/admin/accounts/<user_id>` en méthode `DELETE` avec un utilisateur `user_id` inexistant | L'utilisateur reçoit une réponse **404** avec le message d'erreur *"You can't delete a non existing user"* |
| Utilisateur, dans une organisation X, ayant les droits pour supprimer un utilisateur | se rendre à l'url `/admin/accounts/<user_id>` en méthode `DELETE` avec un utilisateur `user_id` non présent dans l'organisation X | L'utilisateur reçoit une réponse **403** avec le message d'erreur *"You can't delete a user not in your organization"* |
| Utilisateur dont le token a expiré | cliquer sur le bouton de suppression puis cliquer sur le bouton de confirmation de suppression dans la pop-up | L'utilisateur reçoit une réponse **401** avec le message d'erreur *"You are not allowed to do this action (refresh the page if you think you are)"* |

**Comment by enzolouis** [comment]
@jln-brtn

**Comment by jln-brtn** [comment]
Quelques retours : 

1. L'appel de suppression depuis l'interface `admin/accounts/` vers `admin/accounts/<user_id>` en méthode DELETE se fera via un formulaire et respectera [l'exemple d'adonis ](https://docs.adonisjs.com/guides/session#validation-errors-and-flash-messages). On y trouvera une notification de confirmation de suppression.
2. Dans le cas où l'utilisateur essaye de supprimer un utilisateur qui n'existe pas, une erreur doit être retournée.
3. Dans le cas où l'utilisateur essaye de supprimer un utilisateur hors de sa propre organisation, une erreur doit être retournée.
