### ISSUE TITLE
Ajouter un utilisateur

### ISSUE THREAD

**Issue by enzolouis** [crackito-io/crackito#8]
### Description
L'objectif de cette issue est de permettre d'ajouter un utilisateur dans le panel administrateur depuis la page de liste des utilisateurs.

### Cas d'usage

| Acteur | Action | Résultat |
|--------|--------|--------|
| Utilisateur ayant les droits pour ajouter un utilisateur | cliquer sur le bouton d'ajout d'un nouvel utilisateur | L'url  `/admin/accounts/new` en méthode `GET` s'ouvre |
| Utilisateur n'ayant pas les droits d'ajouter un utilisateur | cliquer sur le bouton grisé d'ajout d'un nouvel utilisateur | Rien ne se passe |
| Utilisateur ayant les droits pour ajouter un utilisateur | se rendre à l'url `/admin/accounts/new` en méthode `GET` | La page de création d'un utilisateur est affiché |
| Utilisateur n'ayant pas les droits d'ajouter un utilisateur | se rendre à l'url `/admin/accounts/new` en méthode `GET` | L'utilisateur est retourné sur sa page précédente avec le message d'erreur "You do not have the rights to create users. Please contact your organisation's administrator."|
| Utilisateur ayant les droits pour ajouter un utilisateur | cliquer sur le bouton de confirmation d'ajout d'un nouvel utilisateur | L'url  `/admin/accounts/` en méthode `PUT` s'ouvre |
| Utilisateur ayant les droits pour ajouter un utilisateur | se rendre à l'url `/admin/accounts` en méthode `PUT` | Le nouvel utilisateur est créé |
| Utilisateur n'ayant pas les droits d'ajouter un utilisateur | se rendre à l'url `/admin/accounts` en méthode `PUT` | L'utilisateur est retourné sur sa page précédente avec le message d'erreur "You do not have the rights to create users. Please contact your organisation's administrator."|
| Utilisateur ayant les droits pour ajouter un utilisateur | se rendre à l'url `/admin/accounts` en méthode `PUT` avec des données invalide (nom vide, ...) | L'utilisateur est retourné sur sa page précédente avec le message d'erreur "Invalid user informations : " avec le libellé de l'erreur derrière |

**Comment by enzolouis** [comment]
Au niveau convention pour les champs d'un utilisateur :
Nom : max taille 50
Prénom : max taille 50
Mail : format mail classique, max taille 255
Mot de passe : minimum 1 MAJUSCULE 1 minuscule 1 nombre, max taille 255

Est-ce que le nom/prénom on laisse libre totalement où on restreint ? (pas d'espace & pas de caractères spéciaux) ?
Est-ce que le mot de passe on impose minimum un caractère spécial et une taille minimum ?

**Comment by jln-brtn** [comment]
> Est-ce que le nom/prénom on laisse libre totalement où on restreint ? (pas d'espace & pas de caractères spéciaux) ? 

Pour l'instant, on fait simple, donc pas de restriction

> Est-ce que le mot de passe on impose minimum un caractère spécial et une taille minimum ?

Oui, on peut obliger un caractère spécial et une longueur de 8 minimum
